### ISSUE TITLE
Console hangs completely when exiting

### ISSUE THREAD

**Issue by eroldru** [vinsworldcom/nppConsole#1]
First thing I tried was exiting the console and it froze. Restart helped. Any way to auto restart after exiting?

**Comment by vinsworldcom** [comment]
Yes, typing `exit` in the console will cause problems.  This is a bit of a hack - there is no easy way to embed a conhost Command prompt into an application window so there are some side effects.

Note this is not my code, this is an abandoned plugin that I forked and added some minor updates to.  If you have a fix, please submit a pull request against the develop branch and I'll look to incorporate it.

Cheers.
