### ISSUE TITLE
Not working - v1.2.8.1 x64 (notepad++ v8.6.5)

### ISSUE THREAD

**Issue by Shivter14** [vinsworldcom/nppConsole#11]
![image](https://github.com/vinsworldcom/nppConsole/assets/98386496/8779ca2d-1bab-4f2f-a72d-d78e16b9a148)
Hello; I tried the 32 bit (Win32) version of nppConsole, but somehow that says "Cannot load 64-bit plugin" even though i'm using the 64 bit version of notepad++ and 64 bit Windows 10. So i tried _the 64 bit_ version and that gives me this error.

**Comment by vinsworldcom** [comment]
Cannot reproduce.  It works for me with Notepad++ 8.6.7 64-bit.
