### ISSUE TITLE
pas de fichier .dll

### ISSUE THREAD

**Issue by AqualysS** [vinsworldcom/nppConsole#12]
Bonjour, en téléchargent le dossier, j'ai vu que le fichier NppConsole.dll n'était pas présent, serait-ce car le projet est abandonné ou simplement un bug ? Merci de votre réponse

**Comment by vinsworldcom** [comment]
There is no DLL in the code, you'll need to download a release:

https://github.com/vinsworldcom/nppConsole/releases
