### ISSUE TITLE
Starting folder set to project folder if open, otherwise user folder

### ISSUE THREAD

**Issue by eroldru** [vinsworldcom/nppConsole#2]
After starting the plugin the pwd is the notepad folder in the program files.
This is impractical and I would suggest either using the user folder or when the project explorer is active automatically take that folder.
Another idea would also be opening the console on the folder the currently open file is in.

This is just a nice to have, so no big deal.

**Comment by vinsworldcom** [comment]
For me, it opens in the directory of the currently opened file.  If not file is open, then yes, it's the Notepad++ directory.

Note this is not my code, this is an abandoned plugin that I forked and added some minor updates to.  If you have a fix, please submit a pull request against the develop branch and I'll look to incorporate it.

Cheers.
