### ISSUE TITLE
how to change font ?

### ISSUE THREAD

**Issue by emanueol** [vinsworldcom/nppConsole#3]
Hi sorry, not sure best place to ask question.
I just installed the 32 bits NppConsole and seems to works fine, but I would like to change font , how can i do that ?

Thanks,
Emanuel

**Comment by vinsworldcom** [comment]
@emanueol I don't think you can in the plugin.  Perhaps changing the default font of your actual Command Prompt or Powershell application itself will be reflected when the NppConsole opens.  Note this is a legacy plugin that was abandoned and I just created a 64-bit version and added a few things to it.  I don't pretend to know how it does what it does.  Happy to review a pull request if you have a fix.

Cheers.

**Comment by emanueol** [comment]
thanks for the update.
im only using notepad++ 32bits just because of plugin Hex which I don't
think anyone made it work for 64bits dafly 😥.

Regarding nppconsole, im happy to have interactivy windows cmd prompt. Just
the looks look like cmd.exe itself, so thanks for the suggestion, im going
try update looks and feel in cmd.exe itself and let you know.


Thanks and Kind regards,
Emanuel Oliveira

**Comment by emanueol** [comment]
I found how:
1. launch cmd.exe > click top-left window menu > choose defaults > set font etc..
2. and relaunch Notepad++

Looks good

**Comment by pryrt** [comment]
@emanueol ,

It's even easier: if you open NppConsole window and click in it, then `Alt+Spacebar` and select **Properties** (for the current instance) or **Defaults** (for all instances) , then you have access to the cmd.exe fonts, options, etc -- without having to spawn a separate cmd.exe window.

**Comment by emanueol** [comment]
> @emanueol ,
> 
> It's even easier: if you open NppConsole window and click in it, then `Alt+Spacebar` and select **Properties** (for the current instance) or **Defaults** (for all instances) , then you have access to the cmd.exe fonts, options, etc -- without having to spawn a separate cmd.exe window.

Thats good tip, thanks.
But just now testing NppConsole (didn't used for sometime) and not working.. cant type on it, don't see the prompt any ideas ? Maybe i should check if this is known bug with open issue hmm

![npp_console_not_working](https://user-images.githubusercontent.com/8422412/218273465-02c7bd66-b848-4a1b-bfa5-95d9a3e5d7ff.gif)

**Comment by pryrt** [comment]
When you see that, you need to do Plugins > NppConsole > Restart Console
