### ISSUE TITLE
not working - black window 

### ISSUE THREAD

**Issue by emanueol** [vinsworldcom/nppConsole#6]
Check the animated gif - im using npp 32bits, and I didn't use NppConsole for some time.
It used to work, so do you think anyone can suggest how to make this work ? thanks
![npp_console_not_working](https://user-images.githubusercontent.com/8422412/218274465-ea0c8a8f-e3a7-4a9d-981f-a5a13e17428b.gif)

**Comment by vinsworldcom** [comment]
Try clicking in the NppConsole window and then pressing `Alt+Enter`.

**Comment by emanueol** [comment]
> Try clicking in the NppConsole window and then pressing `Alt+Enter`.

I uninstalled notepad++ 32 bits and installed the 64 bits version and now using NppExec instead of NppConsole.

I can close this issue if you want, or shall I leave it open to give opportunity to others share insights ?
